site_name: EVA

site_url: "https://main.eva-3d.page/"
site_author: "Paweł Kucmus"
site_description: "EVA 3 - 3D printer carriage platform"

copyright: Copyright &copy; 2022 Paweł Kucmus

repo_name: EVA-3D / eva-main
repo_url: https://github.com/EVA-3D/eva-main
edit_uri: ""


plugins:
  - search
  - minify:
      minify_html: true
  - awesome-pages
  - eva-docs-plugin:
      version: 3.0.1
      stls_dir: stls
      onshape_assets_dir: onshape_assets
      assemblies:
        hex_nuts.index:
          title: Hex Nuts
          template_path: overrides/hex_nuts_index.md
          icon: material/download
        heat_insert.index:
          title: Heat Inserts
          template_path: overrides/heat_insert_index.md
          icon: material/download
        hex_nuts.core.corexy: 
          title: CoreXY
          link: https://cad.onshape.com/documents/cb8bd513b980b411d50cd513/w/6e64f1ba8609c44902ccf372/e/2f4214235ff3476304094ba7
        heat_insert.core.corexy: 
          title: CoreXY
          link: https://cad.onshape.com/documents/cb8bd513b980b411d50cd513/w/6e64f1ba8609c44902ccf372/e/ec98b1432b5eb3abcc58f324
        hex_nuts.core.cartesian: 
          title: Cartesian
          link: https://cad.onshape.com/documents/cb8bd513b980b411d50cd513/w/6e64f1ba8609c44902ccf372/e/433c6717dfd0d5150884d0a2
        heat_insert.core.cartesian: 
          title: Cartesian
          link: https://cad.onshape.com/documents/cb8bd513b980b411d50cd513/w/6e64f1ba8609c44902ccf372/e/f946a0f85fa7ec77e6ef7053

        hex_nuts.hotend.rapido: 
          title: Rapido
          link: https://cad.onshape.com/documents/cb8bd513b980b411d50cd513/w/6e64f1ba8609c44902ccf372/e/3909fc96b8808e09f10b28c5
        heat_insert.hotend.rapido: 
          title: Rapido
          link: https://cad.onshape.com/documents/cb8bd513b980b411d50cd513/w/6e64f1ba8609c44902ccf372/e/2c32d9a1ab602c5dce5bad08
        hex_nuts.hotend.mosquito: 
          title: Mosquito
          description: &mosquito |
            !!! warning "Cooling"
                Due to how the Mosquito heat block shape is it's difficult for EVA to achieve proper cooling. You might want to look
                at the [Tri Horn duct](../../bottoms/tri_horn/) to improve the cooling performance.
          link: https://cad.onshape.com/documents/cb8bd513b980b411d50cd513/w/6e64f1ba8609c44902ccf372/e/2b9b0c963501bc147e8e9d92
        heat_insert.hotend.mosquito: 
          title: Mosquito
          description: *mosquito
          link: https://cad.onshape.com/documents/cb8bd513b980b411d50cd513/w/6e64f1ba8609c44902ccf372/e/e43ed049f5cbd645ff6e4fbb
        hex_nuts.hotend.nova: 
          title: Nova
          link: https://cad.onshape.com/documents/cb8bd513b980b411d50cd513/w/6e64f1ba8609c44902ccf372/e/e7a72a605caae17b9eaad465
        heat_insert.hotend.nova: 
          title: Nova
          link: https://cad.onshape.com/documents/cb8bd513b980b411d50cd513/w/6e64f1ba8609c44902ccf372/e/528a37eb3206d38ba20497b6
        hex_nuts.hotend.bmo: 
          title: BMO
          link: https://cad.onshape.com/documents/cb8bd513b980b411d50cd513/w/6e64f1ba8609c44902ccf372/e/a5b2aeaabee29aaffd56d783
        heat_insert.hotend.bmo: 
          title: BMO
          link: https://cad.onshape.com/documents/cb8bd513b980b411d50cd513/w/6e64f1ba8609c44902ccf372/e/3be30a3d48a567e68cf0346a
        hex_nuts.hotend.revo_voron: 
          title: REVO Voron
          link: https://cad.onshape.com/documents/cb8bd513b980b411d50cd513/w/6e64f1ba8609c44902ccf372/e/2133249e56b52c378fd49aee
        heat_insert.hotend.revo_voron: 
          title: REVO Voron
          link: https://cad.onshape.com/documents/cb8bd513b980b411d50cd513/w/6e64f1ba8609c44902ccf372/e/f83669ed7b24c41ee9d3cff8

        hex_nuts.drive.lgx: 
          title: LGX
          link: https://cad.onshape.com/documents/cb8bd513b980b411d50cd513/w/6e64f1ba8609c44902ccf372/e/1d97cf6510faf3fbe5e8298b
        heat_insert.drive.lgx: 
          title: LGX
          link: https://cad.onshape.com/documents/cb8bd513b980b411d50cd513/w/6e64f1ba8609c44902ccf372/e/1d97cf6510faf3fbe5e8298b
        hex_nuts.drive.lgx_lite: 
          title: LGX Lite
          link: https://cad.onshape.com/documents/cb8bd513b980b411d50cd513/w/6e64f1ba8609c44902ccf372/e/c4b1bcdd151521e0c39f3af9
        heat_insert.drive.lgx_lite: 
          title: LGX Lite
          link: https://cad.onshape.com/documents/cb8bd513b980b411d50cd513/w/6e64f1ba8609c44902ccf372/e/c4b1bcdd151521e0c39f3af9
        hex_nuts.drive.orbiter_2_0: 
          title: Orbiter 2.0
          link: https://cad.onshape.com/documents/cb8bd513b980b411d50cd513/w/6e64f1ba8609c44902ccf372/e/e8d566e82b22179849e33eaa
        heat_insert.drive.orbiter_2_0: 
          title: Orbiter 2.0
          link: https://cad.onshape.com/documents/cb8bd513b980b411d50cd513/w/6e64f1ba8609c44902ccf372/e/cd08413a6d72d4950b840b79
        hex_nuts.drive.orbiter_1_5: 
          title: Orbiter 1.5
          link: https://cad.onshape.com/documents/cb8bd513b980b411d50cd513/w/6e64f1ba8609c44902ccf372/e/22cab19756a02c754ebbb3fa
        heat_insert.drive.orbiter_1_5: 
          title: Orbiter 1.5
          link: https://cad.onshape.com/documents/cb8bd513b980b411d50cd513/w/6e64f1ba8609c44902ccf372/e/ef6d0507ceed61c6a4424966
        hex_nuts.drive.bmg: 
          title: BMG
          description: &drive_bmg |
            !!! info "Cable holder"

                The default cable holder mount will not work with BMG, export the "fat" version from 
                [here](https://cad.onshape.com/documents/cb8bd513b980b411d50cd513/w/6e64f1ba8609c44902ccf372/e/863bec3ba9197c227d6573ef).

            This mount is compatible with both BMG and BMG-M, you will need a longer PTFE tube for the former one.
          link: https://cad.onshape.com/documents/cb8bd513b980b411d50cd513/w/6e64f1ba8609c44902ccf372/e/849b78a078391fe8d642e8a8
        heat_insert.drive.bmg: 
          title: BMG
          description: *drive_bmg
          link: https://cad.onshape.com/documents/cb8bd513b980b411d50cd513/w/6e64f1ba8609c44902ccf372/e/849b78a078391fe8d642e8a8

        hex_nuts.cooling_inlet.40mm: 
          title: 40mm based fan
          link: https://cad.onshape.com/documents/cb8bd513b980b411d50cd513/w/6e64f1ba8609c44902ccf372/e/c3506f1f1f26d99f2ad2dc30
        heat_insert.cooling_inlet.40mm: 
          title: 40mm based fan
          link: https://cad.onshape.com/documents/cb8bd513b980b411d50cd513/w/6e64f1ba8609c44902ccf372/e/be90fefe215addad9f977f5a
        hex_nuts.cooling_inlet.dual_5015: 
          title: Dual 5015
          link: https://cad.onshape.com/documents/cb8bd513b980b411d50cd513/w/6e64f1ba8609c44902ccf372/e/31be91812fd80cb662cc72aa
        heat_insert.cooling_inlet.dual_5015: 
          title: Dual 5015
          link: https://cad.onshape.com/documents/cb8bd513b980b411d50cd513/w/6e64f1ba8609c44902ccf372/e/22a5c1644505a7c42e628ee2
        hex_nuts.cooling_inlet.single_5015: 
          title: "Single 5015"
          link: https://cad.onshape.com/documents/cb8bd513b980b411d50cd513/w/6e64f1ba8609c44902ccf372/e/0bd4acbebf8c7a7f2abccc97
        heat_insert.cooling_inlet.single_5015: 
          title: "Single 5015"
          link: https://cad.onshape.com/documents/cb8bd513b980b411d50cd513/w/6e64f1ba8609c44902ccf372/e/0696a26afdfb0fe74ef8a233

        hex_nuts.probes.8mm_probe: 
          title: 8mm Probes
          link: https://cad.onshape.com/documents/cb8bd513b980b411d50cd513/w/6e64f1ba8609c44902ccf372/e/fc88b501d64a4471b218be08
        heat_insert.probes.8mm_probe: 
          title: 8mm Probes
          link: https://cad.onshape.com/documents/cb8bd513b980b411d50cd513/w/6e64f1ba8609c44902ccf372/e/fc88b501d64a4471b218be08
        hex_nuts.probes.bl_touch: 
          title: BL-touch
          link: https://cad.onshape.com/documents/cb8bd513b980b411d50cd513/w/6e64f1ba8609c44902ccf372/e/dbf188e21e46a24ca801cc78
        heat_insert.probes.bl_touch: 
          title: BL-touch
          link: https://cad.onshape.com/documents/cb8bd513b980b411d50cd513/w/6e64f1ba8609c44902ccf372/e/dbf188e21e46a24ca801cc78
        hex_nuts.probes.bl_touch_volcano: 
          title: BL-touch Volcano
          link: https://cad.onshape.com/documents/cb8bd513b980b411d50cd513/w/6e64f1ba8609c44902ccf372/e/ef5aded96603c9fee7224d15
        heat_insert.probes.bl_touch_volcano: 
          title: BL-touch Volcano
          link: https://cad.onshape.com/documents/cb8bd513b980b411d50cd513/w/6e64f1ba8609c44902ccf372/e/ef5aded96603c9fee7224d15

        hex_nuts.cable_management.guide: 
          title: Simple guide
          link: https://cad.onshape.com/documents/cb8bd513b980b411d50cd513/w/6e64f1ba8609c44902ccf372/e/e834d2bbdf7ee06c931da5b3
        heat_insert.cable_management.guide: 
          title: Simple guide
          link: https://cad.onshape.com/documents/cb8bd513b980b411d50cd513/w/6e64f1ba8609c44902ccf372/e/bec2e886d8d4db8d3c1efdd3

        hex_nuts.bottoms.default: 
          title: Default
          description: &bottoms_default |
            This is the exact same duct as the one bundled in the [Core/CoreXY](../../core/corexy) and [Core/Cartesian](../../core/cartesian) assemblies
          link: https://cad.onshape.com/documents/cb8bd513b980b411d50cd513/w/6e64f1ba8609c44902ccf372/e/b4692984999a08ec38f9b9d2
        heat_insert.bottoms.default: 
          title: Default
          description: *bottoms_default
          link: https://cad.onshape.com/documents/cb8bd513b980b411d50cd513/w/6e64f1ba8609c44902ccf372/e/db8f9380f0daa02177a7de41
        hex_nuts.bottoms.volcano: 
          title: Volcano
          link: https://cad.onshape.com/documents/cb8bd513b980b411d50cd513/w/6e64f1ba8609c44902ccf372/e/c8cb348e59d254a62ffbde02
        heat_insert.bottoms.volcano: 
          title: Volcano
          link: https://cad.onshape.com/documents/cb8bd513b980b411d50cd513/w/6e64f1ba8609c44902ccf372/e/4f0a80e4641c1fb364a8a3f6
        hex_nuts.bottoms.tri_horn: 
          title: Tri Horn
          description: &tri_horn |
            This one should be treated as a last resort duct, I made it in a rush as my CHT + Mosquito setup had cooling performance issues.
            Before I figure out a duct that will work better for Mosquito this might help if you have cooling issues.
          link: https://cad.onshape.com/documents/cb8bd513b980b411d50cd513/w/6e64f1ba8609c44902ccf372/e/03eab64073f47dab87c739d5
        heat_insert.bottoms.tri_horn: 
          title: Tri Horn
          description: *tri_horn
          link: https://cad.onshape.com/documents/cb8bd513b980b411d50cd513/w/6e64f1ba8609c44902ccf372/e/3e9f70832e38dd006a427ee7

        hex_nuts.shrouds.small: 
          title: Small
          description: &small |
            Small is the same as [Chonky](../chonky) just with the top cut out.
          link: https://cad.onshape.com/documents/cb8bd513b980b411d50cd513/w/6e64f1ba8609c44902ccf372/e/6d34d6cbba1a58878db5ebd6
        heat_insert.shrouds.small: 
          title: Small
          description: *small
          link: https://cad.onshape.com/documents/cb8bd513b980b411d50cd513/w/6e64f1ba8609c44902ccf372/e/6d34d6cbba1a58878db5ebd6
        hex_nuts.shrouds.chonky: 
          title: Chonky
          description: &chonky |
            Chonky is a tall and light shroud that was the first shroud I made for EVA 3.0. It offers some possibility
            for a tidy build as you can hide some wires behind it (especially the ADXL ones). Comes with a version for those 
            who tend to shove their allen keys in the spinning fan blades.
          link: https://cad.onshape.com/documents/cb8bd513b980b411d50cd513/w/6e64f1ba8609c44902ccf372/e/f51f80720fc79e08730975bf
        heat_insert.shrouds.chonky: 
          title: Chonky
          description: *chonky
          link: https://cad.onshape.com/documents/cb8bd513b980b411d50cd513/w/6e64f1ba8609c44902ccf372/e/f51f80720fc79e08730975bf
        hex_nuts.shrouds.chonkier: 
          title: Chonkier
          description: &chonkier |
            Chonkier is the same as [Chonky](../chonky) but with extra features added. Personally, I don't like it, but it depends 
            on one's taste when it comes to those os I'm leaving it, maybe you'll like it :).
            I made variants with probe cut outs in case stuff like BL-Touch would not fit. 
          link: https://cad.onshape.com/documents/cb8bd513b980b411d50cd513/w/6e64f1ba8609c44902ccf372/e/dd5d7153225c772bde17a69c
        heat_insert.shrouds.chonkier: 
          title: Chonkier
          description: *chonkier
          link: https://cad.onshape.com/documents/cb8bd513b980b411d50cd513/w/6e64f1ba8609c44902ccf372/e/dd5d7153225c772bde17a69c
        hex_nuts.shrouds.tank: 
          title: Tank
          description: &tank | 
            Tank shroud is a shroud I envisioned being "the V-Core 3 shroud" - big and tanky, hides a 8mm probe inside. 

            Caveats:
            
            - it only supports 8mm probes
            - it's thick in Y so a 4020 might not work with it in all applications
          link: https://cad.onshape.com/documents/cb8bd513b980b411d50cd513/w/6e64f1ba8609c44902ccf372/e/7d7c8e7015e5ae3debde11c4
        heat_insert.shrouds.tank: 
          title: Tank
          description: *tank
          link: https://cad.onshape.com/documents/cb8bd513b980b411d50cd513/w/6e64f1ba8609c44902ccf372/e/7d7c8e7015e5ae3debde11c4

theme:
  logo: assets/logo_white_outline.svg
  favicon: assets/logo_white_outline.svg
  language: en
  name: material
  custom_dir: overrides
  palette:
    - scheme: slate 
      primary: green
      accent: lime
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    - scheme: default
      primary: green
      accent: lime
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
  features:
    # - navigation.instant
    # - navigation.top
    # - navigation.sections
    - content.tabs.link
    - search.suggest
    - search.highlight
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.indexes
    - navigation.tracking
    - navigation.expand
    - toc.follow

# extra:
#   consent:
#     title: Cookie consent
#     description: >- 
#       We use cookies to recognize your repeated visits and preferences, as well
#       as to measure the effectiveness of our documentation and whether users
#       find what they're searching for. With your consent, you're helping us to
#       make our documentation better.
#     cookies:
#       analytics:
#         name: Google Analytics
#         checked: false

extra_css:
  - css/extra.css

extra_javascript:
  - https://cdn.jsdelivr.net/npm/es6-promise@4/dist/es6-promise.auto.js
  - https://cdn.scaleflex.it/plugins/js-cloudimage-360-view/2.4.1/js-cloudimage-360-view.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - js/extra.js


markdown_extensions:
  - abbr
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  # - pymdownx.highlight:
  #     linenums_style: pymdownx-inline
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: EVA-3D
      repo: eva-main 
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - toc:
      permalink: true
  - attr_list
  - md_in_html
