site_name: "EVA"
site_url: "https://main.eva-3d.page/"
site_author: "Paweł Kucmus"
site_description: "EVA 2 - 3D printer carriage platform"
edit_uri: ""

copyright: Copyright &copy; 2020 Paweł Kucmus

repo_name: EVA-3D / eva-main
repo_url: https://github.com/EVA-3D/eva-main
version: 2.2.0
  
eva_links:
  org: https://github.com/EVA-3D
  spec: https://github.com/EVA-3D/eva-spec
  main: https://github.com/EVA-3D/eva-main
  bowden: https://github.com/EVA-3D/eva-bowden
  bmg: https://github.com/EVA-3D/eva-bmg
  titan: https://github.com/EVA-3D/eva-titan
  orbiter: https://github.com/EVA-3D/eva-orbiter
  hemera: https://github.com/EVA-3D/eva-hemera
  aero: https://github.com/EVA-3D/eva-aero
  cartesian_idex: https://github.com/EVA-3D/addon-cartesian-idex
  mgn15: https://github.com/EVA-3D/addon-mgn15
  endstops: https://github.com/EVA-3D/addon-endstops
  fan_ducts: https://github.com/EVA-3D/addon-fan-ducts
  probes: https://github.com/EVA-3D/addon-probes

onshape:
  bowden: https://cad.onshape.com/documents/1765b04fac582f6c1c470bd3/w/1cc31596374d6ce51cd23fa9/e/97f38bca98acd8d24f463d78
  bmg: https://cad.onshape.com/documents/8669b75b86d079defa27c647/w/c7d4d8da0ad3b529c7c85328/e/d9184d31fd3592039cc4b5f8
  titan: https://cad.onshape.com/documents/bb6db4fbcd7c5ec5350427f0/w/8da16df4512074fe4659384c/e/d0fc464a4453631a662f183c
  orbiter: https://cad.onshape.com/documents/bb8303124bc8370b6d1924bc/w/8276a22c579374e8b02e9b96/e/7e46b442be945fb22f5c7c28
  aero: https://cad.onshape.com/documents/f3f73361f3085b5d2da46709/w/5849cc3ab4949426cacc9c89/e/12710eca96e60afa44cee204
  hemera: https://cad.onshape.com/documents/371450c83b99fdd5844f4b0c/w/6283a21a1cfe91323a72f862/e/1fc412a1de950c20053d2aaa
  mgn15: https://cad.onshape.com/documents/551442bc5664b4216eddf506/w/16749997681c8bec66757f15/e/ea4ec7fbee5ff4345d4fa96a?configuration=default
  endstops: https://cad.onshape.com/documents/d24027dd78e7164add26b5f5/w/0615251dcae8664926ca1aa2/e/e01d9ebd9e9d0542d74812ce
  fan_ducts: https://cad.onshape.com/documents/cdbbab45bc478a93284f0aa0/w/8c39e85696457ae4cc840a32/e/fec27277bac9449b909144a3
  cartesian_idex: https://cad.onshape.com/documents/a2d21b0faa4745fa21bc844e/w/d7f14dfeeee2e68fe2f1149b/e/fcd1503d3995b7b7473cc831
  probes: https://cad.onshape.com/documents/94cafeab52e3dfa0a28bae89/w/99794094315556b24b5664ec/e/586b7b03d8fce1234cd4debb

theme:
  logo: assets/logo_white_outline.svg
  favicon: assets/logo_white_outline.svg
  language: en
  name: material
  custom_dir: overrides
  palette:
    scheme: slate
    primary: green
    accent: lime
  features:
    - navigation.instant
    # - navigation.sections
    - navigation.expand
    - search.suggest
    - search.highlight

plugins:
  - search
  - minify:
      minify_html: true
  - awesome-pages
  - eva-3d-plugin
  - macros:
      modules: [eva_3d.bom]
  - exclude:
      glob:
        - "*.zip"

extra_css:
  - css/extra.css

extra_javascript:
  - https://cdn.scaleflex.it/plugins/js-cloudimage-360-view/2.4.1/js-cloudimage-360-view.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - js/extra.js

markdown_extensions:
  - abbr
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  # - pymdownx.highlight:
  #     linenums_style: pymdownx-inline
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: EVA-3D
      repo: eva-main 
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - toc:
      permalink: true
